### ISSUE TITLE
Merge with VITfaculty API? 

### ISSUE THREAD

**Issue by aneesh-neelam** [kishore-narendran/VITauth-Backend#6]
I propose we merge this and [VITfaculty](https://github.com/kishore-narendran/VITfaculty-Backend). 

That makes it easier to manage the codebase and data. Also, they are very lightweight on their own, without much functionality.

**Comment by kishore-narendran** [comment]
I was thinking the same. My dilemma is the name of the app. :P
Also, I think let's post this for later. Let's get the individual functioning up and running along with the client applications and then we will merge them. Merging them will be easy. Let's maintain in coherence in URLs and Database collections and all until then.

**Comment by aneesh-neelam** [comment]
I'm merging [VITfaculty-Backend](https://github.com/kishore-narendran/VITfaculty-Backend) and this now. Tell me if you want me to hold off.

**Comment by aneesh-neelam** [comment]
Commit [02a00de470f6ee6927795fb61631fa3ec737b66f](https://github.com/aneesh-neelam/VITauth/commit/02a00de470f6ee6927795fb61631fa3ec737b66f) does this. Consider issue fixed. 

Please move all development and discussion to [VITauth](https://github.com/aneesh-neelam/VITauth). 

There are still things left to do, like Project Wiki, Deployment etc.
